<a href="https://colab.research.google.com/github/iiph1/229352-StatisticalLearning/blob/main/660510773_lab08_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [ ]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a = torch.tensor(8)
b = torch.tensor(9)
print(a)
print(b)
print(a+b)

tensor(8)
tensor(9)
tensor(17)


### Convert a tensor to scalar

In [ ]:
a.item()

8

### Creating 2D tensor

In [ ]:
A = torch.tensor([[1, 2], [3, 4]])
print(A)

tensor([[1, 2],
        [3, 4]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
A.numpy()

array([[1, 2],
       [3, 4]])

### Convert from numpy array to tensor

In [ ]:
B = np.array([[1, 2], [3, 4]])

C = torch.from_numpy(B)
print(C)

tensor([[1, 2],
        [3, 4]])


## Basic operations

In [ ]:
D = 2*C

E = C - 10

print(D)
print(E)

tensor([[2, 4],
        [6, 8]])
tensor([[-9, -8],
        [-7, -6]])


### Matrix multiplication

In [ ]:
print(torch.matmul(D, E))
print(torch.mm(D, E))
print(D @ E)

tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])


### Matrix transpose

In [ ]:
print(C)
print( C.t() )

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


In [ ]:
I = torch.tensor([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]],
                  [[-1, -2], [-3, -4]]])

print(I)
print()
torch.transpose(I, 1, 2)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[-1, -2],
         [-3, -4]]])



tensor([[[ 1,  3],
         [ 2,  4]],

        [[ 5,  7],
         [ 6,  8]],

        [[-1, -3],
         [-2, -4]]])

## Creating a specific type of tensor

In [ ]:
# print(torch.zeros(2,3))
# print(torch.ones(2,3))
# print(torch.rand(2,3))
# print(torch.randn(2,3))  # sample each number from N(0, 1)
# print(torch.arange(9))

In [ ]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2, 2, 2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [ ]:
torch.rand(2, 3)

tensor([[0.1047, 0.9522, 0.7557],
        [0.6441, 0.7640, 0.0398]])

In [ ]:
torch.randn(2, 3) # มากกว่า -1 แต่น้อยกว่า  1    ได้

tensor([[-0.8354, -0.0454,  0.2803],
        [-0.2073,  1.3253,  1.1880]])

## Tensor's shape

### Checking the shape of a tensor

In [ ]:
F = torch.zeros((4, 5))
print(F.shape)
print(F.size())

torch.Size([4, 5])
torch.Size([4, 5])


In [ ]:
F = torch.zeros((2, 4, 5))
print(F.shape)

torch.Size([2, 4, 5])


In [ ]:
F.size()

torch.Size([2, 4, 5])

### Changing the shape of a tensor

In [ ]:
G = torch.arange(6)
print(G.view(2, 3))
print(G.reshape(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
G = torch.arange(6)
print(G.shape)

torch.Size([6])


In [ ]:
G1 = G.reshape(2, 3)
G1

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
G2 = G.view(2, 3)
G2

tensor([[0, 1, 2],
        [3, 4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
H = torch.arange(6)
H1 = - torch.arange(6)
I = torch.stack([H, H1, H, H1], axis=0) # แถว
J = torch.stack([H, H1, H, H1], axis=1) # column
print(I)
print(J)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 0, -1, -2, -3, -4, -5],
        [ 0,  1,  2,  3,  4,  5],
        [ 0, -1, -2, -3, -4, -5]])
tensor([[ 0,  0,  0,  0],
        [ 1, -1,  1, -1],
        [ 2, -2,  2, -2],
        [ 3, -3,  3, -3],
        [ 4, -4,  4, -4],
        [ 5, -5,  5, -5]])


In [ ]:
# concatenate

I = torch.cat([H, H, H, H], axis=0)
print(I)
H1 = torch.tensor([[1, 2], [3, 4]])
#J = torch.cat([H, H, H, H], axis=1) # จะเกิด error เพราะไม่มีแกนที่ 1
#print(J)

tensor([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])


### Squeezing a tensor (removing an extra dimension)

In [ ]:
# [[1,2]] this is (1,2) tensor, want (2,)
print("H=", H) # shape = (6,)
K = H.reshape(1,6)
print("K=", K)
print(K.shape)

H= tensor([0, 1, 2, 3, 4, 5])
K= tensor([[0, 1, 2, 3, 4, 5]])
torch.Size([1, 6])


In [ ]:
print(K.squeeze())

tensor([0, 1, 2, 3, 4, 5])


In [ ]:
K1 = K.squeeze() # ลบวงเล็ที่ซ้ำกัน

In [ ]:
K1.shape

torch.Size([6])

In [ ]:
# H.shape = (6, )
L = H.unsqueeze(axis=0)  # L.shape(1, 6)
M = H.unsqueeze(axis=1)  # L.shape(6, 1)
print(L)
print(M)

tensor([[0, 1, 2, 3, 4, 5]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])


In [ ]:
H

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
H1= H.unsqueeze(axis=0)

In [ ]:
H1.shape

torch.Size([1, 6])

In [ ]:
H.unsqueeze(axis=1) # เพิ่มแกนที่ 1 เข้ามาแทน

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])

In [ ]:
H2 = H.unsqueeze(axis=1)
H2.shape

torch.Size([6, 1])

## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available()

True

In [ ]:
Q = torch.tensor([1, 2, 3])
print(Q.device)

cpu


In [ ]:
R = Q.to('cuda')
print(Q.device)
print(R.device)

cpu
cuda:0


In [ ]:
R = Q.to('cuda')
R.device

device(type='cuda', index=0)

In [ ]:
R1 = Q.cuda()
R1.device

device(type='cuda', index=0)

In [ ]:
G.numpy()

array([0, 1, 2, 3, 4, 5])

In [ ]:
R.cpu().numpy()

array([1, 2, 3])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [ ]:
# 1. Create three random N(0,1) tensors: X, b and e
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)


In [ ]:
# 2. Create a tensor that contains only 1's with shape (200, 1)
ones = torch.ones(200, 1)

In [ ]:
# 3. Add the ones as the FIRST column
X = torch.cat([ones, X], dim=1)

In [ ]:
# 4. y = X b + e
y = X @ b + e

In [ ]:
# 5. b_hat = (X^T X)^(-1) X^T y
# ใช้ torch.linalg.inv(XtX)
XtX = X.T @ X
XtX_inv = torch.linalg.inv(XtX)
b_hat = XtX_inv @ X.T @ y

In [ ]:
# 6. y_hat = X b_hat
y_hat = X @ b_hat

In [ ]:
# 7. Convert to NumPy and compute MSE (ไม่หาร 2)
y_np = y.detach().numpy()
y_hat_np = y_hat.detach().numpy()
mse = np.mean((y_np - y_hat_np)**2)

In [ ]:
print("Estimated coefficients (b_hat):")
print(b_hat)
print("\nMean Squared Error (MSE):", mse)

Estimated coefficients (b_hat):
tensor([[ 1.7165],
        [-0.7309],
        [-0.9717],
        [-0.1320],
        [-0.4141],
        [ 0.2622],
        [ 0.6137],
        [-1.5305]])

Mean Squared Error (MSE): 1.007746
